#! /bin/sh

### BEGIN INIT INFO
# Provides:             telepid 
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         
# Short-Description:    TelePi run telegram-cli under screen session
### END INIT INFO

# Some things that run always
touch /var/lock/telepid

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script TelePi "
    screen -d -m -S telepi
    screen -S telepi -X stuff 'su - telepi\n'
    screen -S telepi -X stuff '/opt/tg/bin/telegram-cli -k /opt/tg/tg-server.pub -W -s telepi.lua 2>&1\n'
    ;;
  stop)
    echo "Stopping script TelePi"
    screen -X -S telepi quit
    ;;
  *)
    echo "Usage: /etc/init.d/telepi {start|stop}"
    exit 1
    ;;
esac

exit 0
